### ISSUE TITLE
RF data protocol

### ISSUE THREAD

**Issue by ankitsohaliya** [Grayda/go-orvibo#3]
Hi Grayda,

Anyone have decoded RF protocol and frame structure communicated between RF Switch and Allone.

**Comment by Grayda** [comment]
Check out https://github.com/Grayda/go-orvibo/blob/master/orvibo.go#L221-L250 which is all the RF stuff I've got so far.

I don't know if the RF is two way (e.g. AllOne talks to RF, RF can talk back to the AllOne) but I strongly suspect it's **one way only** (e.g. Allone talks to RF only).

This is based on Wireshark packet captures from someone who contacted me via email. I asked him to press buttons on the RF switch and watch his phone for data coming from the AllOne, but nothing happened, so I assume that it's one way only.

Hope this helps!

**Comment by clyra** [comment]
Do you think it's possible for the AllOne to control other RF devices? I mean, not only "orvibos" but funry, livolo and other chinese brands? I just got a livolo one and would be very nice if I could control it with my AllOne.

**Comment by Grayda** [comment]
I've never worked with the Livolo (or the RF on the Orvibo actually, as I don't own any of the RF switches and support was "theoretical") but if Livolo talks over 433mhz, then maybe? I don't know enough about RF support on the AllOne to know if it's possible. 

I suspect that the AllOne constructs packets and sends them out, rather than the user constructing the packets (meaning that the Livolo wouldn't be supported, unless they used the same packet format as the AllOne), but as I said, RF support has been tested, but from my end, is "theoretical" because I don't own the equipment, or the tools for testing.

So the best answer I can give is "maybe". You might be better off with something like the Broadlink RM2 Pro, which costs about the same as an AllOne and can "learn" button presses and such, meaning if the switch was compatible, you could control it using your phone.

**Comment by clyra** [comment]
I would like to try... I found this: http://forum.arduino.cc/index.php?topic=153525.0 which has the code for the buttons of the livolo switch. I saw that the "func EmitRF" has a "RF string" which i guess is what should  be transmited to the device. Any guess on what should be on this string?

**Comment by Grayda** [comment]
Even after reading that post, I'm still unsure, as the WiWo app (that controls the AllOne) doesn't pass raw 433mhz to the AllOne for sending. Instead, WiWo sends the AllOne an RF "ID" (a code that the RF switch and AllOne agree on) and a state (00 for off, 01 for on) and maybe something else. But I suspect that when it leaves the AllOne to go to the RF switch, it's in a very specific format.

If you really want to try, do the following (and note, these steps may not work, due to it being a product from another brand). Also note that the communication between the RF, AllOne and WiWo are simplified here, so you get an idea of why it may or may not work
- Put the wall switch into learning mode. On the Orvibo RF switch, you hold down a button until it beeps). The Livolo might be different.
- Open the WiWo app on your phone. Add a new switch. WiWo gives it a randomly assigned ID (e.g. ABCD)
- Press the newly created switch in the app. The AllOne sends "ABCD" (and probably other data) out. If the Livolo is similar enough to the AllOne, it'll be listening for a new ID and will accept "ABCD" and store it.
- Try turning the wall switch on and off in the WiWo app. If it works, then yes, you can use the AllOne (and my code) with the Livolo. If it **doesn't** work, then you can't use the Livolo (more on why, in a moment)
- If the switch is controllable via WiWo, you'll need to find out the switch ID. You could do this by opening the WiWo settings database and looking for the ID (which would probably require root or a jailbroken phone, and something I could provide limited assistance with), or you can capture the traffic between WiWo and the AllOne using Wireshark. See https://discuss.ninjablocks.com/t/how-to-capture-packets-from-wifi-enabled-items/2629 for a tutorial. 
- Once you have the ID, use EmitRF in go-orvibo to control the lights. I haven't worked on the RF stuff for a while, but I think you'd use: `EmitRF(true, "2b00" + [YOUR ID HERE])`

So if the switch isn't controllable, then the AllOne is sending a specific RF message (e.g. [YOURID] + [ON / OFF]) and the Livolo might be expecting [LIVOLO HEADER] + [ON / OFF] + [YOURID] or something, and that's not something you can control, unless you open up the AllOne and reprogram the chip inside.

**Comment by clyra** [comment]
Thanks for the explanation! I'm out of luck then... Wiwo/AllOne can't control the livolo switch, and I was hoping that we could access "hiding" functions on AllOne thru your app. But, it seems that the RF protocol is "hardcoded" on AllOne, right?

**Comment by Grayda** [comment]
Yep, it seems like it is "hard coded". At one point I even pulled the WiWo app apart and checked out all the RF emitting stuff, and there was no mention of hidden RF stuff (as Orvibo has no need for it, otherwise you'd buy someone else's switches, and not theirs, I guess). 

As mentioned earlier, the Broadlink RM2 Pro seems to be your best bet. I made a start on reverse engineering the protocol (without using their SDK, because where's the fun in just using their software? :smile:) but it got complicated fast, as I think there was encryption, private keys and a stupid amount of port hopping needed to control stuff.

Another thing that popped into mind is the timing of the 433mhz. I originally wrote the Orvibo library to use with a Ninja Block (a home automation device) and found that the Ninja Block didn't recognise the AllOne's RF signals. It was 433mhz, but the timing was different to the compatible devices Ninja Blocks supported and the NB wasn't seeing the signal. I doubt that's the case, but it's just a thought.

But with all that said, you could try coercing the AllOne into sending arbitrary RF signals by finding out what the Livolo is sending, and trying EmitRF with a few combinations. For example, if the Livolo is sending "ABC12345", you could try `EmitRF("45", "ABC123")` or `EmitRF("BC", "A123")` and so on. That's grasping at straws, however.

**Comment by Grayda** [comment]
I'm going to close this issue, as there hasn't been a response in over a week. Feel free to open it or a new, should you have any more questions :)
